- id: rust-fmt
  name: rust fmt
  description: "rust formatter"
  entry: rustfmt
  language: rust
  types: [file]
  types_or: [rust]
  args: ["-l"]
- id: cargo-clippy
  name: cargo clippy
  description: "rust linter (clippy)"
  entry: cargo clippy
  language: rust
  types: [file]
  types_or: [rust]
  args: ["--all-features", "--all-targets"]
  pass_filenames: false
